model_id: "microsoft/Florence-2-large"
dataset_id: "diffusers/ShotDEAD-v0"
mixed_precision: "fp16"
cache_dir: null
num_proc: 4
batch_size: 16
gradient_accumulation_steps: 4
gradient_checkpointing: false
resume_from_checkpoint: false
max_grad_norm: 1.0
freeze_vision_tower: true
use_lora: false
use_8bit_adam: false
epochs: 20
lr: 1e-6
eval_steps: 1000
max_val_item_count: 1000
save_steps: 2000
report_to: "wandb"
